export const districts = [
  "Agar Malwa",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Airport Quarantine",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alappuzha",
  "Aligarh",
  "Alipurduar",
  "Alirajpur",
  "Almora",
  "Alwar",
  "Ambala",
  "Ambedkar Nagar",
  "Amethi",
  "Amravati",
  "Amreli",
  "Amritsar",
  "Amroha",
  "Anand",
  "Anantapur",
  "Anantnag",
  "Angul",
  "Anjaw",
  "Anuppur",
  "Araria",
  "Aravalli",
  "Ariyalur",
  "Arwal",
  "Ashoknagar",
  "Auraiya",
  "Aurangabad",
  "Aurangabad",
  "Ayodhya",
  "Azamgarh",
  "BSF Camp",
  "Bagalkote",
  "Bageshwar",
  "Baghpat",
  "Bahraich",
  "Balaghat",
  "Balangir",
  "Balasore",
  "Ballari",
  "Ballia",
  "Balod",
  "Baloda Bazar",
  "Balrampur",
  "Balrampur",
  "Bametara",
  "Banaskantha",
  "Banda",
  "Bandipora",
  "Banka",
  "Bankura",
  "Banswara",
  "Barabanki",
  "Baramulla",
  "Baran",
  "Bareilly",
  "Bargarh",
  "Barmer",
  "Barnala",
  "Barwani",
  "Bastar",
  "Basti",
  "Bathinda",
  "Beed",
  "Begusarai",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Betul",
  "Bhadohi",
  "Bhadrak",
  "Bhagalpur",
  "Bhandara",
  "Bharatpur",
  "Bharuch",
  "Bhavnagar",
  "Bhilwara",
  "Bhind",
  "Bhiwani",
  "Bhojpur",
  "Bhopal",
  "Bidar",
  "Bijapur",
  "Bijnor",
  "Bikaner",
  "Bilaspur",
  "Bilaspur",
  "Birbhum",
  "Bokaro",
  "Botad",
  "Boudh",
  "Budaun",
  "Budgam",
  "Bulandshahr",
  "Buldhana",
  "Bundi",
  "Burhanpur",
  "Buxar",
  "Chamarajanagara",
  "Chamba",
  "Chamoli",
  "Champawat",
  "Champhai",
  "Chandauli",
  "Chandigarh",
  "Chandrapur",
  "Changlang",
  "Charkhi Dadri",
  "Chatra",
  "Chengalpattu",
  "Chennai",
  "Chhatarpur",
  "Chhindwara",
  "Chhota Udaipur",
  "Chikkaballapura",
  "Chikkamagaluru",
  "Chitradurga",
  "Chitrakoot",
  "Chittoor",
  "Chittorgarh",
  "Churu",
  "Coimbatore",
  "Cooch Behar",
  "Cuddalore",
  "Cuttack",
  "Dadra and Nagar Haveli",
  "Dahod",
  "Dakshin Bastar Dantewada",
  "Dakshin Dinajpur",
  "Dakshina Kannada",
  "Daman",
  "Damoh",
  "Dang",
  "Darbhanga",
  "Darjeeling",
  "Datia",
  "Dausa",
  "Davanagere",
  "Dehradun",
  "Delhi",
  "Deogarh",
  "Deoghar",
  "Deoria",
  "Devbhumi Dwarka",
  "Dewas",
  "Dhalai",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharmapuri",
  "Dharwad",
  "Dhenkanal",
  "Dholpur",
  "Dhule",
  "Dibang Valley",
  "Dimapur",
  "Dindigul",
  "Dindori",
  "Diu",
  "Doda",
  "Dumka",
  "Dungarpur",
  "Durg",
  "East Champaran",
  "East Garo Hills",
  "East Godavari",
  "East Jaintia Hills",
  "East Kameng",
  "East Khasi Hills",
  "East Siang",
  "East Singhbhum",
  "Ernakulam",
  "Erode",
  "Etah",
  "Etawah",
  "Evacuees",
  "Faridabad",
  "Faridkot",
  "Farrukhabad",
  "Fatehabad",
  "Fatehgarh Sahib",
  "Fatehpur",
  "Fazilka",
  "Ferozepur",
  "Firozabad",
  "Foreign Evacuees",
  "Gadag",
  "Gadchiroli",
  "Gajapati",
  "Ganderbal",
  "Gandhinagar",
  "Ganganagar",
  "Ganjam",
  "Garhwa",
  "Gariaband",
  "Gaurela Pendra Marwahi",
  "Gautam Buddha Nagar",
  "Gaya",
  "Ghaziabad",
  "Ghazipur",
  "Gir Somnath",
  "Giridih",
  "Godda",
  "Gomati",
  "Gonda",
  "Gondia",
  "Gopalganj",
  "Gorakhpur",
  "Gumla",
  "Guna",
  "Guntur",
  "Gurdaspur",
  "Gurugram",
  "Gwalior",
  "Hamirpur",
  "Hamirpur",
  "Hanumangarh",
  "Hapur",
  "Harda",
  "Hardoi",
  "Haridwar",
  "Hassan",
  "Hathras",
  "Haveri",
  "Hazaribagh",
  "Hingoli",
  "Hisar",
  "Hnahthial",
  "Hooghly",
  "Hoshangabad",
  "Hoshiarpur",
  "Howrah",
  "Idukki",
  "Indore",
  "Italians",
  "Jabalpur",
  "Jagatsinghpur",
  "Jaipur",
  "Jaisalmer",
  "Jajpur",
  "Jalandhar",
  "Jalaun",
  "Jalgaon",
  "Jalna",
  "Jalore",
  "Jalpaiguri",
  "Jammu",
  "Jamnagar",
  "Jamtara",
  "Jamui",
  "Janjgir Champa",
  "Jashpur",
  "Jaunpur",
  "Jehanabad",
  "Jhabua",
  "Jhajjar",
  "Jhalawar",
  "Jhansi",
  "Jhargram",
  "Jharsuguda",
  "Jhunjhunu",
  "Jind",
  "Jodhpur",
  "Junagadh",
  "Kabeerdham",
  "Kaimur",
  "Kaithal",
  "Kalaburagi",
  "Kalahandi",
  "Kalimpong",
  "Kallakurichi",
  "Kamle",
  "Kancheepuram",
  "Kandhamal",
  "Kangra",
  "Kannauj",
  "Kannur",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kanyakumari",
  "Kapurthala",
  "Karaikal",
  "Karauli",
  "Kargil",
  "Karnal",
  "Karur",
  "Kasaragod",
  "Kasganj",
  "Kathua",
  "Katihar",
  "Katni",
  "Kaushambi",
  "Kendrapara",
  "Kendujhar",
  "Khagaria",
  "Khandwa",
  "Khargone",
  "Khawzawl",
  "Kheda",
  "Khordha",
  "Khowai",
  "Khunti",
  "Kinnaur",
  "Kiphire",
  "Kishanganj",
  "Kishtwar",
  "Kodagu",
  "Koderma",
  "Kohima",
  "Kolar",
  "Kolasib",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Kondagaon",
  "Koppal",
  "Koraput",
  "Korba",
  "Koriya",
  "Kota",
  "Kottayam",
  "Kozhikode",
  "Kra Daadi",
  "Krishna",
  "Krishnagiri",
  "Kulgam",
  "Kullu",
  "Kupwara",
  "Kurnool",
  "Kurukshetra",
  "Kurung Kumey",
  "Kushinagar",
  "Kutch",
  "Lahaul and Spiti",
  "Lakhimpur Kheri",
  "Lakhisarai",
  "Lalitpur",
  "Latehar",
  "Latur",
  "Lawngtlai",
  "Leh",
  "Lepa Rada",
  "Lohardaga",
  "Lohit",
  "Longding",
  "Longleng",
  "Lower Dibang Valley",
  "Lower Siang",
  "Lower Subansiri",
  "Lucknow",
  "Ludhiana",
  "Lunglei",
  "Madhepura",
  "Madhubani",
  "Madurai",
  "Maharajganj",
  "Mahasamund",
  "Mahe",
  "Mahendragarh",
  "Mahisagar",
  "Mahoba",
  "Mainpuri",
  "Malappuram",
  "Malda",
  "Malkangiri",
  "Mamit",
  "Mandi",
  "Mandla",
  "Mandsaur",
  "Mandya",
  "Mansa",
  "Mathura",
  "Mau",
  "Mayurbhanj",
  "Meerut",
  "Mehsana",
  "Mirzapur",
  "Moga",
  "Mokokchung",
  "Mon",
  "Moradabad",
  "Morbi",
  "Morena",
  "Mumbai",
  "Mungeli",
  "Munger",
  "Murshidabad",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysuru",
  "Nabarangapur",
  "Nadia",
  "Nagapattinam",
  "Nagaur",
  "Nagpur",
  "Nainital",
  "Nalanda",
  "Namakkal",
  "Namsai",
  "Nanded",
  "Nandurbar",
  "Narayanpur",
  "Narmada",
  "Narsinghpur",
  "Nashik",
  "Navsari",
  "Nawada",
  "Nayagarh",
  "Neemuch",
  "Nilgiris",
  "Niwari",
  "North 24 Parganas",
  "North Garo Hills",
  "North Tripura",
  "Nuapada",
  "Nuh",
  "Osmanabad",
  "Other State",
  "Other State",
  "Other State",
  "Other State",
  "Other State",
  "Other State",
  "Other State",
  "Other State",
  "Others",
  "Pakke Kessang",
  "Pakur",
  "Palakkad",
  "Palamu",
  "Palghar",
  "Pali",
  "Palwal",
  "Panchkula",
  "Panchmahal",
  "Panipat",
  "Panna",
  "Papum Pare",
  "Parbhani",
  "Paschim Bardhaman",
  "Paschim Medinipur",
  "Patan",
  "Pathanamthitta",
  "Pathankot",
  "Patiala",
  "Patna",
  "Pauri Garhwal",
  "Perambalur",
  "Peren",
  "Phek",
  "Pilibhit",
  "Pithoragarh",
  "Porbandar",
  "Prakasam",
  "Pratapgarh",
  "Pratapgarh",
  "Prayagraj",
  "Puducherry",
  "Pudukkottai",
  "Pulwama",
  "Punch",
  "Pune",
  "Purba Bardhaman",
  "Purba Medinipur",
  "Puri",
  "Purnia",
  "Purulia",
  "Rae Bareli",
  "Raichur",
  "Raigad",
  "Raigarh",
  "Railway Quarantine",
  "Raipur",
  "Raisen",
  "Rajgarh",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri",
  "Rajsamand",
  "Ramanagara",
  "Ramanathapuram",
  "Ramban",
  "Ramgarh",
  "Rampur",
  "Ranchi",
  "Ranipet",
  "Ratlam",
  "Ratnagiri",
  "Rayagada",
  "Reasi",
  "Rewa",
  "Rewari",
  "Ribhoi",
  "Rohtak",
  "Rohtas",
  "Rudraprayag",
  "Rupnagar",
  "S.A.S. Nagar",
  "S.P.S. Nellore",
  "Sabarkantha",
  "Sagar",
  "Saharanpur",
  "Saharsa",
  "Sahibganj",
  "Saiha",
  "Saitual",
  "Salem",
  "Samastipur",
  "Samba",
  "Sambalpur",
  "Sambhal",
  "Sangli",
  "Sangrur",
  "Sant Kabir Nagar",
  "Saraikela-Kharsawan",
  "Saran",
  "Satara",
  "Satna",
  "Sawai Madhopur",
  "Sehore",
  "Seoni",
  "Serchhip",
  "Shahdol",
  "Shahid Bhagat Singh Nagar",
  "Shahjahanpur",
  "Shajapur",
  "Shamli",
  "Sheikhpura",
  "Sheohar",
  "Sheopur",
  "Shi Yomi",
  "Shimla",
  "Shivamogga",
  "Shivpuri",
  "Shopiyan",
  "Shrawasti",
  "Siang",
  "Siddharthnagar",
  "Sidhi",
  "Sikar",
  "Simdega",
  "Sindhudurg",
  "Singrauli",
  "Sipahijala",
  "Sirmaur",
  "Sirohi",
  "Sirsa",
  "Sitamarhi",
  "Sitapur",
  "Sivaganga",
  "Siwan",
  "Solan",
  "Solapur",
  "Sonbhadra",
  "Sonipat",
  "South 24 Parganas",
  "South Garo Hills",
  "South Tripura",
  "South West Garo Hills",
  "South West Khasi Hills",
  "Sri Muktsar Sahib",
  "Srikakulam",
  "Srinagar",
  "State Pool",
  "Subarnapur",
  "Sukma",
  "Sultanpur",
  "Sundargarh",
  "Supaul",
  "Surajpur",
  "Surat",
  "Surendranagar",
  "Surguja",
  "Tapi",
  "Tarn Taran",
  "Tawang",
  "Tehri Garhwal",
  "Tenkasi",
  "Thane",
  "Thanjavur",
  "Theni",
  "Thiruvallur",
  "Thiruvananthapuram",
  "Thiruvarur",
  "Thoothukkudi",
  "Thrissur",
  "Tikamgarh",
  "Tirap",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvannamalai",
  "Tonk",
  "Tuensang",
  "Tumakuru",
  "Udaipur",
  "Udham Singh Nagar",
  "Udhampur",
  "Udupi",
  "Ujjain",
  "Umaria",
  "Una",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unnao",
  "Unokoti",
  "Upper Dibang Valley",
  "Upper Siang",
  "Upper Subansiri",
  "Uttar Bastar Kanker",
  "Uttar Dinajpur",
  "Uttara Kannada",
  "Uttarkashi",
  "Vadodara",
  "Vaishali",
  "Valsad",
  "Varanasi",
  "Vellore",
  "Vidisha",
  "Vijayapura",
  "Viluppuram",
  "Virudhunagar",
  "Visakhapatnam",
  "Vizianagaram",
  "Wardha",
  "Washim",
  "Wayanad",
  "West Champaran",
  "West Garo Hills",
  "West Godavari",
  "West Jaintia Hills",
  "West Kameng",
  "West Khasi Hills",
  "West Siang",
  "West Singhbhum",
  "West Tripura",
  "Wokha",
  "Y.S.R. Kadapa",
  "Yadgir",
  "Yamunanagar",
  "Yanam",
  "Yavatmal",
  "Zunheboto",
];
